# Generated by Django 4.2.7 on 2023-11-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('repetitions', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
