# Generated by Django 4.2.7 on 2023-11-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
