# Generated by Django 4.2.7 on 2023-11-10 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_remove_exercise_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='date',
        ),
    ]
