# Generated by Django 4.2.7 on 2023-11-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_exercise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='incremental_weight',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
