# Generated by Django 4.2.7 on 2023-11-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_exercise_incremental_weight_alter_exercise_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.routine')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(blank=True, through='exercises.RoutineExercise', to='exercises.exercise'),
        ),
    ]
