# Generated by Django 4.2.7 on 2023-11-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_routine_routineexercise_routine_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineexercise',
            name='repetitions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='sets',
            field=models.IntegerField(null=True),
        ),
    ]
