# Generated by Django 4.2.7 on 2023-11-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_alter_routineexercise_repetitions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineexercise',
            name='repetitions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
